sudo: false
language: node_js
node_js:
    - "14"
cache:
    directories:
        - node_modules
script:
    - npm run build
    - npm run test:ci
    - npm run coveralls:ci
notifications:
    webhooks: https://coveralls.io/webhook